config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :courses do
    resources :assignments, except: :index
  end


  get 'help',             to: 'help_requests#new'
  post 'help_requests',   to: 'help_requests#create'
  get 'help_email_sent',  to: 'help_requests#help_email_sent'

  get 'about',            to: 'pages#about'
  get 'contact',          to: 'pages#contact'
  get 'privacy',          to: 'pages#privacy'
  get 'terms',            to: 'pages#terms'
  get 'account',          to: 'pages#account'
  get '/robots.:format',  to: 'pages#robots'

  root 'pages#home'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  has_many :course_assignments
  has_many :courses, through: :course_assignments
  has_many :grades
  has_many :students, through: :grades
  belongs_to :category

  validates :name, presence: true
  validates :user, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :category, presence: true
  validates :weight, presence: true
  has_many :assignments
  belongs_to :user
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :course_enrollments
  has_many :students, through: :course_enrollments

  has_many :course_assignments
  has_many :assignments, through: :course_assignments
  belongs_to :user
  validates :name, presence: true
  validates :user, presence: true
end

app/models/course_assignment.rb
class CourseAssignment < ActiveRecord::Base
  belongs_to :course
  belongs_to :assignment
  belongs_to :user
  validates :course_id, :assignment_id, presence: true
end

app/models/course_enrollment.rb
class CourseEnrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :student
  belongs_to :user
  validates :student_id, :course_id, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base

  validates :points_earned, presence: true
  belongs_to :student
  belongs_to :assignment
  belongs_to :user

  def self.for_student(student)
    where(student: student)
  end
end

app/models/help_request.rb
class HelpRequest < ActiveRecord::Base
  belongs_to :user
  validates :email, presence: true
  validates :message, presence: true
end

app/models/student.rb
def presence_of_a_name
  validate :presence_of_a_name
  has_many :course_enrollments
  has_many :courses, through: :course_enrollments
  belongs_to :user

  has_many :grades
  has_many :assignments, through: :grades

  def presence_of_a_name
    unless first_name.present? || last_name.present?
      errors.add(:first_name, 'Must have a first or last name.')
      errors.add(:last_name, 'Must have a first or last name.')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable,
         :lockable

  has_many :assignments, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :course_assignments, dependent: :destroy
  has_many :course_enrollments, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :help_requests, dependent: :destroy
  has_many :students, dependent: :destroy
  has_many :grades, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  respond_to :html, :js, :json

  rescue_from Pundit::NotAuthorizedError, with: :permission_denied

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || courses_path
  end

  def permission_denied
    head :forbidden
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def show
    authorize(@assignment)
  end

  def edit
    @course = current_user.courses.find(params[:course_id])
  end

  def new
    @course = current_user.courses.find(params[:course_id])
    @assignment = current_user.assignments.new
    @assignment.course_id = @course.id
    authorize(@assignment)
  end

  def create
    @assignment = current_user.assignments.new(assignment_params)
    authorize(@assignment)
    if @assignment.save
      redirect_to(:back)
    else
      render :new
    end
  end

  def update
    authorize(@assignment)
    if @assignment.update(assignment_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
    authorize(@assignment)
    @assignment.destroy
    redirect_to :back
  end

  private

  def assignment_params
    params.require(:assignment).permit(:name, :date_due, :category, :points_earned, :total_points, :course_id)
  end

  def set_assignment
    @assignment = current_user.assignments.find(params[:id])
  end

  def set_course
    @course = current_user.courses.find(params[:course_id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @courses = current_user.courses
  end

  def show
    authorize(@course)
  end

  def new
    @course = current_user.courses.new
    authorize(@course)
  end

  def edit
    authorize(@course)
  end

  def create
    @course = current_user.courses.new(course_params)
    authorize(@course)
    @courses = current_user.courses
    if @course.save
      respond_with(@course, location: @course)
    else
      render :new
    end
  end

  def update
    authorize(@course)
    if @course.update(course_params)
      respond_with @course, location: @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize(@course)
    @course.destroy
    redirect_to courses_url, notice: 'Course was successfully destroyed.'
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :time, :period, :user, :section)
  end
end

app/controllers/help_requests_controller.rb
class HelpRequestsController < ApplicationController
  def new
    @help_request = HelpRequest.new
  end

  def create
    help_request = HelpRequest.new(help_request_params)

    if help_request.save
      HelpRequestMailer.new_request(help_request).deliver_later
      redirect_to help_email_sent_path
    else
      render :new
    end
  end

  def help_email_sent
  end

  private

  def help_request_params
    params.require(:help_request).permit(:email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end

  def privacy
  end

  def terms
  end

  def communication
  end

  def home
  end

  def account
  end

  def robots
    respond_to :text
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
  @students = current_user.students
  respond_with(@students)
end

def show
  respond_with(@student)
end

def new
  @student = current_user.students.new
  respond_with(@student)
end

def edit
end

def create
  @student = current_user.students.new(student_params)

  if @student.save
    respond_with @student
  else
    render :new
  end
end

def update
  @student.update(student_params)
  redirect_to(:back)
end

def destroy
  @student.destroy
  redirect_to(:back)
end

private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :grade_level, :birth_date, :course_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Gradejoy"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/views/assignments/_assignment_buttons.html.erb
<%= link_to 'Delete Assignment', course_assignment_path(@course.id, @assignment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this assignment?' }, class: "btn btn-xs btn-danger qa-delete" %>
<%= link_to 'Edit Assignment', edit_course_assignment_path(@course.id, @assignment.id), class: "btn btn-xs btn-primary qa-edit-assignment", id: "edit_assignment" %>

app/views/assignments/_form.html.erb
<%= form_for([@course, @assignment]) do |f| %>
  <% if @assignment.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@assignment.errors.count, 'error') %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_page? new_course_assignment_path %>
    <h3>Create New Assignment</h3>
  <% else %>
    <h3>Edit <%= @assignment.name %></h3>
  <% end %>

  <%= f.label :name %> (required)
  <%= f.text_field :name, class: 'form-control form-control-inline qa-assignment-name' %><br /><br />

  <%= f.label :date_due %>
  <%= f.datetime_select :date_due, start_year: DateTime.current.year, end_year: 2015, ampm: true %><br /><br />

  <%= f.label :category %>
  <%= f.text_field :category, class: 'form-control form-control-inline qa-assignment-category' %><br /><br />

  <%= f.label :total_points %>
  <%= f.number_field :total_points, class: 'form-control form-control-inline qa-assignment-total-points' %><br /><br />

  <%= f.text_field :course_id, value: @course.id, readonly: true, class: 'none' %>

  <div class='actions'>
      <%= f.submit 'Submit', class:'btn btn-primary qa-submit-assignment' %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<% provide(:title, "Edit Assignment") %>

<%= render 'form' %>

<%= link_to 'Back to Course', course_path(@course), class: 'btn  btn-primary space-top' %>

app/views/assignments/new.js.erb
$('#create-assignment-form').html("<%= j (render 'form') %>");
$('.create-assignment').click(function(){
  $('#create-assignment-form').toggle();
});

app/views/assignments/show.js.erb
var assignmentId = "#assignment-<%= j @assignment.id.to_s %>"
var assignmentButtonsId = ".assignment-buttons-<%= j @assignment.id.to_s %>"

$(assignmentButtonsId).html("<%= j (render 'assignment_buttons') %>");
$(assignmentId).click(function(){
  $(assignmentButtonsId).toggle();
});

app/views/courses/_course_name_ajax.html.erb
<% provide(:title, @course.name) %>
<h2><%= @course.name %></h2>

app/views/courses/_courses_table.html.erb
<div class="table-responsive" id="courses-table">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Course Name</th>
        <th>Course ID</th>
        <th>Time</th>
        <th>Period</th>
        <th>Section</th>
        <th>Created</th>
      </tr>
    </thead>

    <tbody id="courses_table">
      <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.name, course, class: "qa-course-#{course.id}" %></td>
        <td><%= course.id %></td>
        <td><%= course.time.strftime("%I:%M %p") %></td>
        <td><%= course.period %></td>
        <td><%= course.section %></td>
        <td><%= course.created_at.strftime("%A, %B %d, %Y, at %I:%M %p") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/courses/_form.html.erb
<%= form_for @course, remote: true do |f| %>
  <% if @course.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@course.errors.count, 'error') %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_page? new_course_path %>
    <h3>Create New Course</h3>
  <% else %>
    <h3>Edit Course</h3>
  <% end %>
  <%= f.label :name %>(required)
  <%= f.text_field :name, class: 'form-control form-control-inline space-top-bottom qa-course-name' %><br />

  <%= f.label :time_of_day %>
  <%= f.time_select :time, ampm: true, class: 'form-control form-control-inline space-bottom qa-course-time' %><br />

  <%= f.label :period %>
  <%= f.text_field :period, class: 'form-control form-control-inline space-top-bottom qa-course-period' %><br />

  <%= f.label :section %>
  <%= f.text_field :section, class: 'form-control form-control-inline space-bottom qa-course-section' %><br />

  <div class='actions'>
    <%= f.submit 'Submit', class:'btn btn-primary qa-submit-course space-bottom' %>
  </div>

<% end %>

app/views/courses/_main_table.html.erb
<div class="table-responsive" id="main-table">
  <table class="table table-bordered table-hover">
    <thead>
      <tr id="student_info_header">
        <th>First Name</th>
        <th>Last Name</th>
        <th>Grade Level</th>
        <th>Average</th>
        <% @course.assignments.each do |assignment| %>
          <th id="assignment-<%= assignment.id.to_s %>"><%= link_to assignment.name, course_assignment_path(@course.id, assignment.id), class: "qa-assignment-#{assignment.id}", remote: true %><span class="assignment-buttons-<%=assignment.id %> space-left"></span></th>
        <% end %>
      </tr>
    </thead>


  </table>
</div>

app/views/courses/_new_course.html.erb
<tr>
  <td><%= link_to @course.name, @course, class: "qa-course-#{@course.id}" %></td>
  <td><%= @course.id %></td>
  <td><%= @course.time.strftime("%I:%M %p") %></td>
  <td><%= @course.period %></td>
  <td><%= @course.section %></td>
  <td><%= @course.created_at.strftime("%A, %B %d, %Y, at %I:%M %p") %></td>
</tr>

app/views/courses/create.js.erb
$('#courses_table').append("<%= j (render 'new_course') %>");
$('#course-form').slideUp(350);

app/views/courses/edit.js.erb
$('#course-form').html("<%= j (render 'form') %>");
$('#edit-course').click(function(){
  $('#course-form').toggle();
});

app/views/courses/index.html.erb
<% if notice %>
  <p class='alert alert-success'><%= notice %></p>
<% end %>
<% if alert %>
  <p class='alert alert-danger'><%= alert %></p>
<% end %>
<% provide(:title, 'Courses') %>

<h2 class='space-bottom qa-courses-header'>Courses</h2>

<%= render 'courses_table' %>

<%= link_to 'Create New Course', new_course_path, class: 'btn btn-primary space-top-bottom qa-create-course', id: 'create-course', remote: true %>

<div id='course-form'></div>

app/views/courses/new.js.erb
$('#course-form').html("<%= j (render 'form') %>");
$('#create-course').click(function(){
  $('#course-form').toggle();
});

app/views/courses/show.html.erb
<% provide(:title, @course.name) %>

<h2 class="course-title" id="course-name"><%= @course.name %></h2>
<h2 id="course-name-change" class="course-title"></h2>

<%= link_to 'Edit Course', edit_course_path(@course), class: "btn btn-primary qa-edit-course", id: "edit-course", remote: true %>

<%= link_to 'Delete Course', course_path, method: :delete, data: { confirm: 'Are you sure you want to delete this course?' }, class: "btn btn-danger space-left qa-delete-course" %> <br /><br />

<div id="updated-course"></div>

<div id="course-form"></div>

<h3>Enrolled Students</h3>

<%= render 'main_table' %>

<%= link_to "Create New Assignment", new_course_assignment_path(@course), class: "btn btn-warning qa-create-assignment space-top-bottom qa-create-assignment", remote: true %><br />

<div id="create-assignment-form"></div>

<%= link_to 'Back to Courses List', courses_path, class: "btn btn-primary qa-back-to-courses-list space-top" %>

app/views/courses/update.js.erb
$('#course-form').slideUp(350);
$('#course-name').replaceWith("<%= j render 'course_name_ajax' %>");
$('html head').find('title').text(" Gradejoy | <%=@course.name %>");

app/views/help_requests/_form.html.erb
<%= form_for(@help_request) do |f| %>
  <% if @help_request.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@help_request.errors.count, 'error') %> prohibited this message from being sent:</h2>

      <ul>
      <% @help_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :email %>(required)
  <%=f.email_field :email, class: 'form-control form-control-inline space-bottom qa-email' %><br />

  <%= f.label :message %>(required)<br />
  <%=f.text_area :message, class: 'form-control form-control-inline space-bottom qa-message', id: 'help-request' %>

  <div class='actions'>
    <%= f.submit 'Submit', class:'btn btn-primary qa-submit' %>
  </div>


<% end %>

app/views/help_requests/help_email_sent.html.erb
<h4 class='qa-email-sent-message'>Your message has been sent. A Gradejoy representative will reply within 48 hours.</h4>

app/views/help_requests/new.html.erb
<% provide(:title, "Help") %>
<h3>Help</h3><br />
<h4>Frequently Asked Questions</h4>
<ol>
  <li>Q: How do I create an account?</li><br />
  <p>On the Gradejoy homepage, click "Login" at the top right. Then click "Sign Up" on the next page.</p>
</ol>
<br />
<p>If your question was not answered by the information on this page, please fill out the form below and your question will be answered as soon as possible.</p>
<br />

<%= render 'form' %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <p>
    <%= link_to "About Gradejoy", about_path %> &middot;
    <%= link_to "Contact Us", contact_path %> &middot;
    <%= link_to "Privacy", privacy_path %> &middot;
    <%= link_to "Terms", terms_path%> &middot;
    <%= link_to "Source Code", "https://github.com/robertlandreaux/gradejoyV2", :target => "_blank" %>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
      <%= link_to "Gradejoy", root_path, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Courses", courses_path %></li>
        <li><%= link_to "Account", edit_user_registration_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<% else %>
    <%= link_to "Gradejoy", root_path, class:"navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Contact Us', contact_path %></li>
        <li><%= link_to 'Help', help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Login or Sign up', new_user_session_path) %></li>
      </ul>
    </div>
   </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Gradejoy">
  <meta name="author" content="Robert C. Landreaux">
  <%= favicon_link_tag "favicon.ico" %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
      <%= render "layouts/navbar" %>
      <div id="container">
        <%= yield %>
      </div>
  </div> <!-- wrap -->
  <%= render "layouts/footer" %>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h3>About Gradejoy</h3>
<br />
<p>Gradejoy is a simple, intuitive, and easy-to-use gradebook application for teachers.</p>

app/views/pages/account.html.erb
<% provide(:title, "Account") %>
<h3>My Account</h3>
<br />
<%= link_to "Change your password or cancel your account", edit_user_registration_path, class:"btn btn-primary" %>

app/views/pages/communication.html.erb
<% provide(:title, "Communication") %>
<h3>Communication</h3>
<br />
<p>This feature is coming in the future.</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h3>Contact Us</h3>
<br />
<p>You can contact Robert Landreaux at robertlandreaux@gmail.com</p>
<p>You can also find the Gradejoy source code <u><%= link_to "here", "https://github.com/robertlandreaux/gradejoyV2", :target => "_blank" %></u>.</p>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <h2>Experience Gradejoy.</h2>
  <br />
  <p class="lead">Gradejoy is a gradebook application for teachers.</p>
  <br />
  <h4>Begin by clicking "Login or Sign up" at the top right of the page.</h4>
  <br /><h4>After signing up, please check your email and confirm your email address<br /> by clicking on the link in the email. Check your Spam folder if you do not see the email in your Inbox.</h4>
  <br /><h4>This application is still under construction. Many features are still in progress.</h4>
</div>

app/views/pages/index.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron">
  <h2>Experience Gradejoy.</h2>
  <br />
  <p class="lead">Gradejoy is a simple, intuitive, and easy-to-use gradebook application for teachers and students.</p>
  <br />
  <h4>Begin by clicking "Login or Sign up" at the top right of the page.</h4>
  <br /><h4>After signing up, please check your email and confirm your email address<br /> by clicking on the link in the email. Check your Spam folder if you do not see the email in your Inbox.</h4>
  <!--<br /><h2>Gradejoy requires JavaScript to function properly.</h2> -->
  <br /><h4>This application is still under construction. Many features are still in progress.</h4>
</div>

app/views/pages/privacy.html.erb
<% provide(:title, "Privacy") %>
<h3>Privacy</h3>
<br />
<p>We do not share or sell your account data.</p>

app/views/pages/robots.text.erb
User-Agent: *
Disallow:
Crawl-Delay: 20

app/views/pages/terms.html.erb
<% provide(:title, "Terms") %>
<h3>Terms</h3>
<br />
<p>Gradejoy is a free service. Accounts which have inappropriate content or are used for ill purposes will be deleted.</p>